###
POST http://localhost:3000/register/
Content-Type: application/json 

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}


POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8

###
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8



###
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8



###
GET http://localhost:3000/tweets/3/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJuYW1lIjoiSm9lIEJpZGVuIiwidXNlcm5hbWUiOiJKb2VCaWRlbiIsInBhc3N3b3JkIjoiJDJiJDEwJDJhcmU2QmE2OW9pL0NhaTRhVC9WTS50N0FPN1RzUXgvLk9nei43WEc0cWp1TWlsMHY4MGFxIiwiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTcyNDEyMjY2OX0.k1Du7VQtxqBWserztB7iGjxY3uAtQDW-z39yp1C0jX8
 

###
GET http://localhost:3000/tweets/4/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8


###
GET http://localhost:3000/tweets/2/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8



###
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8



###
POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8


{
   "tweet": "The Mornings..."
}

###
DELETE http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE3MjQwNTQwODB9.Ef-5heomrim-vme9FMzCtzJhwumpiCd5JECDPfb55X8










